enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

npmScopes:
  harness:
    npmRegistryServer: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: TOKEN

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
